---
- name: GREP process ID
  shell: >
    pgrep nginx
  register: PID
  
- name: check whether nginx process running or not | if not then install NGNIX
  apt:
    - name: nginx
      become: yes
      state: enabled
  debug:
    msg: "Process is already running do nothing"
  when: PID.results == false
  
- name: Copy config file
  copy:
    src: /$HOME/ashnik_assessment/nginx.conf
    dest: /$HOME/roles/ashnik_assessment/templates/nginx_conf.j2
  delegate_to: 52.87.52.87

- name: Replace the nginx config file
  template:
    src: /$HOME/roles/ashnik_assessment/templates/nginx_conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx
  handlers:
    - name: Restart nginx
      service: 
        - name: nginx
          state: restarted